source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftlySalesforce_Example' do
  pod "SwiftlySalesforce", :path => "../"
end

target 'SwiftlySalesforce_Tests' do
  pod "SwiftlySalesforce", :path => "../"
end
