source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SwiftlySalesforce_Example', :exclusive => true do
  pod "SwiftlySalesforce", :path => "../"
end

target 'SwiftlySalesforce_Tests', :exclusive => true do
  pod "SwiftlySalesforce", :path => "../"

  
end
